# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

name: AzureARMDeploy

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: |
        az deployment group create \
          --name StorageAccountDeployment \
          --resource-group savdevgithubdeploy \
          --template-file /ARMTemplates/StorageAccount.json \
          --parameters storageAccountType=Standard_GRS
